import rawShowcase from "../generated/showcase-data.json";
import {siteUrl} from "../lib/site";

export interface ShowcaseDataset {
  citation: string;
  fixtureCells: number;
  heldOutPatients: number[];
  license: string;
  licenseUrl: string;
  markers: string[];
  name: string;
  patients: number;
  populations: string[];
  referencePatients: number[];
  repository: string;
  studyCells: number;
  upstreamEvents: number;
}

export interface MarkerSeries {
  density: number[];
  population: string;
}

export interface MarkerPanel {
  edges: number[];
  marker: string;
  series: MarkerSeries[];
}

export interface PatientComposition {
  fractions: number[];
  patient: number;
  role: string;
}

export interface MethodPoint {
  bins: number;
  heldOutEfficiency: number | null;
  macroRmse: number;
  minimumBinCount: number | null;
}

export interface MethodSeries {
  isScoreQuant: boolean;
  key: string;
  label: string;
  points: MethodPoint[];
}

export interface ShowcaseData {
  comparison: {
    budgets: number[];
    methods: MethodSeries[];
    unbinnedBaseline: {label: string; macroRmse: number; perClassRmse: number[]};
  };
  dataset: ShowcaseDataset;
  exploration: {markerScale: string; markers: MarkerPanel[]; patients: PatientComposition[]};
  headline: {
    bins: number;
    heldOutEfficiency: number;
    macroRmse: number;
    unbinnedMacroRmse: number;
  };
  scoreSchema: {parameters: string[]};
}

/**
 * Generated by `website/scripts/generate_showcase.py` from committed artifacts.
 * Never edit by hand; run `pnpm generate:showcase`.
 */
export const showcaseData = rawShowcase as unknown as ShowcaseData;

/** The five-dimensional score table the Lab runs on, fetched rather than bundled. */
export interface ScoreStructure {
  distinctPlanePositions: number;
  perPopulation: {cells: number; meanFirstScore: number; population: string; spread: number}[];
  rows: number;
}

export interface LabScoreTable {
  dimensions: number;
  license: string;
  populationNames: string[];
  populations: number[];
  rows: number;
  schema: {parameters: string[]};
  scores: number[][];
  structure: ScoreStructure;
  weights: number[];
}

const SCORES_URL = siteUrl("showcase-data/flowcyt-scores.json");

/**
 * Load the score table on demand.
 *
 * It is ~300 KB and only the playground needs it, so it stays out of the
 * bundle and out of the narrative route's critical path.
 */
export async function loadLabScores(signal?: AbortSignal): Promise<LabScoreTable> {
  const response = await fetch(SCORES_URL, signal === undefined ? {} : {signal});
  if (!response.ok) throw new Error(`The FlowCyt score table is unavailable (${String(response.status)}).`);
  return (await response.json()) as LabScoreTable;
}
