import {useCallback, useEffect, useRef, useState} from "react";

import {parseScoreFile} from "./parseScoreFile";
import {loadLabScores} from "../data/showcase";
import {portalData} from "../data/portal";
import type {ScoreRow} from "./protocol";

export type DatasetId = "gaussian" | "flowcyt" | "local";

export interface ScoreTable {
  /** Short provenance line shown beside the controls. */
  detail: string;
  id: DatasetId;
  label: string;
  schema: string[] | undefined;
  scores: ScoreRow[];
  weights: number[];
}

const GAUSSIAN: ScoreTable = {
  detail: "Generated by the repository fixture with seed 28; the native NumPy result is pinned in CI.",
  id: "gaussian",
  label: "Gaussian fixture",
  schema: ["mu_x", "mu_y"],
  scores: portalData.scoreSpace.points.map((row) => row as ScoreRow),
  weights: portalData.scoreSpace.weights,
};

export interface ScoreTableState {
  /** Load the study's five-dimensional mixture scores, fetched on demand. */
  chooseFlowCyt: () => void;
  chooseGaussian: () => void;
  error: string | null;
  loadFile: (file: File) => void;
  loading: boolean;
  table: ScoreTable;
}

/**
 * Own the score table the Lab is running on.
 *
 * The FlowCyt table is ~300 KB and is fetched only when chosen, so opening the
 * Lab to try the built-in fixture costs nothing. A local file is read in this
 * tab and never sent anywhere -- there is no server to send it to.
 */
export function useScoreTable(): ScoreTableState {
  const [table, setTable] = useState<ScoreTable>(GAUSSIAN);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const abortRef = useRef<AbortController | null>(null);

  useEffect(() => () => abortRef.current?.abort(), []);

  const chooseGaussian = useCallback((): void => {
    abortRef.current?.abort();
    setError(null);
    setTable(GAUSSIAN);
  }, []);

  const chooseFlowCyt = useCallback((): void => {
    abortRef.current?.abort();
    const controller = new AbortController();
    abortRef.current = controller;
    setLoading(true);
    setError(null);
    loadLabScores(controller.signal)
      .then((payload) => {
        setTable({
          detail: `${payload.rows.toLocaleString()} cells × ${String(payload.dimensions)} score dimensions · CC BY-NC-SA 4.0`,
          id: "flowcyt",
          label: "FlowCyt mixture scores",
          schema: payload.schema.parameters,
          scores: payload.scores as ScoreRow[],
          weights: payload.weights,
        });
      })
      .catch((cause: unknown) => {
        if (controller.signal.aborted) return;
        setError(cause instanceof Error ? cause.message : String(cause));
      })
      .finally(() => {
        if (!controller.signal.aborted) setLoading(false);
      });
  }, []);

  const loadFile = useCallback((file: File): void => {
    abortRef.current?.abort();
    setLoading(true);
    setError(null);
    parseScoreFile(file)
      .then((parsed) => {
        setTable({
          detail: `${parsed.scores.length.toLocaleString()} rows × ${String(parsed.scores[0]?.length ?? 0)} dimensions, read in this tab`,
          id: "local",
          label: file.name,
          schema: parsed.schema,
          scores: parsed.scores as ScoreRow[],
          weights: parsed.weights,
        });
      })
      .catch((cause: unknown) => {
        setError(cause instanceof Error ? cause.message : String(cause));
      })
      .finally(() => {
        setLoading(false);
      });
  }, []);

  return {chooseFlowCyt, chooseGaussian, error, loadFile, loading, table};
}
